/** Shared CHANGELOG parsing and docs-sync helpers. No network. */

export const UNRELEASED = "Unreleased";

export function parseChangelog(text) {
  const lines = text.split(/\r?\n/);
  const sections = [];
  let current = null;
  for (const line of lines) {
    const heading = line.match(/^## \[([^\]]+)\](?: - (\d{4}-\d{2}-\d{2}))?$/);
    if (heading) {
      if (current) sections.push(current);
      current = {
        version: heading[1],
        date: heading[2] || null,
        lines: [],
      };
      continue;
    }
    if (current) current.lines.push(line);
  }
  if (current) sections.push(current);
  return sections;
}

export function sectionBody(section) {
  return section.lines.join("\n").trim();
}

export function sectionHasEntries(section) {
  return section.lines.some((line) => /^\s*-\s+\S/.test(line));
}

export function unreleasedSection(sections) {
  return sections.find((section) => section.version === UNRELEASED) ?? null;
}

export function datedSection(sections, version) {
  return (
    sections.find((section) => section.version === version && section.date) ??
    null
  );
}

export function behaviorPath(path) {
  const normalized = path.replaceAll("\\", "/");
  if (
    normalized === "docs/reference/changelog.md" ||
    normalized === "docs/reference/release-audit.md"
  ) {
    return false;
  }
  return (
    normalized.startsWith("src/") ||
    normalized.startsWith("src-tauri/src/") ||
    normalized.startsWith("docs/guide/") ||
    normalized.startsWith("docs/reference/") ||
    normalized === "README.md" ||
    normalized === "SECURITY.md"
  );
}

export function renderDocsChangelog(changelogText) {
  return [
    "---",
    "title: Changelog",
    "description: User-facing OnionGate changes, kept in lockstep with CHANGELOG.md.",
    "---",
    "",
    "<!-- Generated by scripts/sync-release-docs.mjs. Edit CHANGELOG.md, then run make changelog-sync. -->",
    "",
    changelogText.trim(),
    "",
  ].join("\n");
}

export function renderReleaseAudit({ version, range, commits }) {
  const list =
    commits.length === 0
      ? "- (no commits in this range)"
      : commits.map((line) => `- \`${line}\``).join("\n");
  return [
    "---",
    "title: Release audit trail",
    "description: Commit subjects included in each packaged version. Subjects only — no diffs, paths, or secrets.",
    "---",
    "",
    "<!-- Generated by scripts/sync-release-docs.mjs. Do not hand-edit. -->",
    "",
    "# Release audit trail",
    "",
    "Each packaged version lists **commit subjects** since the previous tagged",
    "release. This is the audit trail for docs and GitHub release notes. It is",
    "not a substitute for the user-facing [changelog](/reference/changelog).",
    "",
    "Do not paste bridge lines, onion keys, credentials, public IPs, or full",
    "command lines into commit subjects.",
    "",
    `## ${version}`,
    "",
    range ? `Range: \`${range}\`.` : "Range: current `HEAD` (no previous tag).",
    "",
    list,
    "",
  ].join("\n");
}

export function validateChangelogText(text) {
  const failures = [];
  if (!text.startsWith("# Changelog")) {
    failures.push("CHANGELOG.md must start with '# Changelog'");
  }
  const sections = parseChangelog(text);
  const unreleased = unreleasedSection(sections);
  if (!unreleased) {
    failures.push("CHANGELOG.md must contain '## [Unreleased]'");
  }
  return { sections, unreleased, failures };
}

export function requireTrailForChanges({
  behaviorChanged,
  versionBumped,
  newVersion,
  sections,
}) {
  const failures = [];
  if (!behaviorChanged) {
    return failures;
  }
  if (versionBumped) {
    const dated = datedSection(sections, newVersion);
    if (!dated) {
      failures.push(
        `version is ${newVersion} but CHANGELOG.md has no '## [${newVersion}] - YYYY-MM-DD' section`,
      );
    } else if (!sectionHasEntries(dated)) {
      failures.push(`CHANGELOG.md section [${newVersion}] has no entries`);
    }
    return failures;
  }
  const unreleased = unreleasedSection(sections);
  if (!unreleased || !sectionHasEntries(unreleased)) {
    failures.push(
      "behavior files changed; add a bullet under ## [Unreleased] in CHANGELOG.md",
    );
  }
  return failures;
}
